steps:
  - read: npm_scope 
    from: env.SCOPE

  - read: extension_name
    from: git.remote_name

  - read: extension_description
    from: env.DESCRIPTION

  - read: repo_url
    from: git.remote_url


  - copy: .recipes/default/README.md
    to: 'README.md'
  - update: README.md
  
  - copy: .recipes/default/package.json
    to: 'package.json'
  - update: package.json

  - copy: .recipes/default/package.json
    to: 'package.json'
  - update: package.json

  - copy: .recipes/default/patternfly-docs/content/extensions/patternfly-extension-seed/examples/basic.md
    to: 'patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/examples/basic.md'

  - copy: .recipes/default/patternfly-docs/content/extensions/patternfly-extension-seed/examples/Basic.tsx
    to: 'patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/examples/Basic.tsx'

  - copy: .recipes/default/patternfly-docs/content/extensions/patternfly-extension-seed/design-guidelines/design-guidelines.md
    to: 'patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/design-guidelines/design-guidelines.md'

  - copy: .recipes/default/patternfly-docs/generated/index.js
    to: patternfly-docs/generated/index.js
  - update: patternfly-docs/generated/index.js

  - copy: .recipes/default/patternfly-docs/generated/extensions/patternfly-extension-seed/design-guidelines.js
    to: 'patternfly-docs/generated/extensions/{{ extension_name | kebab-case }}/design-guidelines.js'

  - copy: .recipes/default/patternfly-docs/generated/extensions/patternfly-extension-seed/react.js
    to: 'patternfly-docs/generated/extensions/{{ extension_name | kebab-case }}/react.js'

  